export const dashboardActionTypes = {
  getDataBoard: "GET_DASHBORD_STATS",
  dashbordStatsReceived: "DASHBORD_STATS_RECEIVED",
  getHotspotData: "GET_HOTSPOT_DATA",
  hotspotDataReceived: "HOTSPOT_DATA_RECEIVED",
  addLocation: "ADD_LOCATION",
  locationAddedSucessfully: "LOCATION_ADDED_SUCESSFULLY",
  setCenter: "SET_CENTER",
  setCenterSucessfully: "SET_CENTER_SUCESSFULLY",
  setInfectionStatus: "SET_INFECTION_STATUS",
  deleteLocation: "DELETE_LOCATION",
  deleteLocationSuccess: "DELETE_LOCATION_SUCCESS",
  deleteLocationError: "DELETE_LOCATION_ERROR",
  setTimeStamp: "SET_SETTIME_STAMP",
  clearDataPatient: "CLEAR_DATA_PATIENT",
};
